AWSTemplateFormatVersion: '2010-09-09'
Description: Module Security Groups

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  PublicSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Anywhere
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: [{Key: Name, Value: Public-SG-CF}]

  PrivateSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Public SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSG
      Tags: [{Key: Name, Value: Private-SG-CF}]

Outputs:
  PublicSGId:
    Value: !Ref PublicSG
  PrivateSGId:
    Value: !Ref PrivateSG